version: '3'

services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    image: swagger/mongodb
    env_file: .env
    volumes:
      - .docker/mongo/data/db:/data/db
    ports:
      - 27017:27017
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - mongodb
    image: swagger/app
    volumes:
      - .:/opt/app
    # command: bash -c "python loader.py && python server/app.py"
    # command: python server/app.py
    command: ./bootstrap.sh
    stdin_open: true
    tty: true
    links:
      - mongodb
    ports:
      - 5000:5000
