# Generated by Django 2.0.4 on 2018-04-20 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsrer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecipEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('precip', models.DecimalField(blank=True, decimal_places=10, max_digits=50, null=True)),
                ('raingage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsrer.Raingage')),
            ],
            options={
                'verbose_name': 'Precip Events',
                'verbose_name_plural': 'Precip Events',
            },
        ),
    ]
