# Generated by Django 2.0.4 on 2018-04-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raingage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('watershed_id', models.CharField(blank=True, max_length=5, null=True)),
                ('gage_id', models.CharField(blank=True, max_length=125, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('elevation', models.IntegerField(blank=True, null=True)),
                ('err', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Raingage',
                'verbose_name_plural': 'Raingages',
            },
        ),
    ]
