# Generated by Django 2.0.4 on 2018-04-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwgew', '0002_precipevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precipevent',
            name='month',
        ),
        migrations.RemoveField(
            model_name='precipevent',
            name='precip',
        ),
        migrations.RemoveField(
            model_name='precipevent',
            name='year',
        ),
        migrations.AddField(
            model_name='precipevent',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='precipevent',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='precipevent',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='precipevent',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='precipevent',
            name='time_est',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
